### ISSUE TITLE
Bernard-Soulier syndrome, type A1 (recessive) not being prioritzied 231200 

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/LIRICAL#407]
Jannovar correctly annotated the variant.
It is homozygous ALT in the phenopacket.
chr17:4836699C>G	STOP_GAINED	GP1BA:NM_000173.5:c.800C>G:p.(S267*)	.
The GP1BA gene is not present in the output of the phenopacket

**Comment by pnrobinson** [comment]
The simulated gene GP1BA is not present in the genotypeMap.

**Comment by pnrobinson** [comment]
The correct variant is getting added to the VCF:
```
$ grep 4836699 /tmp/single-vcf-simulator-Patient\ 3-5755937724998832311.vcf 
chr17	4836699	.	C	G	.	.	=.	GT	1/1
```

**Comment by pnrobinson** [comment]
OK, so the problem is that the following code is not returning an EntrezGene ID for the GP1BA gene (it should be this:https://www.ncbi.nlm.nih.gov/gene/2811) gut the ``getGeneId`` method is returning an empty string).

```
VariantAnnotation va = jannovarVariantAnnotator.annotate(contig, start, ref, alt);
VariantEffect variantEffect = va.getVariantEffect();
 if (!variantEffect.isOffExome()) {
                        String genIdString = va.getGeneId(); // for now assume this is an Entrez Gene ID
                        String symbol = va.getGeneSymbol();
                        TermId geneId;
```

**Comment by pnrobinson** [comment]
@julesjacobsen  I think there may be an issue with the jannovar file for ucsc packaged in Exomiser. It does not contain the Entrez Gene id for GP1BA. If I use the jannovar files for refseq or ensembl, then the same phenopacket jumps from rank 63 to rank 1.
Shlebak-2015-GP1BA-Patient_3.json

**Comment by damiansm** [comment]
@pnrobinson Is it possible to run LIRICAL on the ensembl.ser file? I think I tried doing this before as I use the ensembl one for the GEL cases. However, changing the option in LIRICAL did not seem to switch behaviour?

**Comment by julesjacobsen** [comment]
Yes, it appears that the geneId is missing from the UCSC data. Its extremely unlikely that this is an Exomiser protobuf conversion issue as all the transcript sources are imported using the exact same mechanism. It suggests this is either a Jannovar or UCSC issue.

1902_ucsc.ser

```
[VariantAnnotation{genomeAssembly=hg19, chromosome=17, chromosomeName='17', start=4836699, ref='C', alt='G', geneSymbol='GP1BA', geneId='', variantEffect=STOP_GAINED, annotations=[TranscriptAnnotation{variantEffect=STOP_GAINED, geneSymbol='GP1BA', accession='uc021tob.1', hgvsGenomic='g.4836699C>G', hgvsCdna='c.800C>G', hgvsProtein='p.(Ser267*)', distanceFromNearestGene=-2147483648}, TranscriptAnnotation{variantEffect=STOP_GAINED, geneSymbol='GP1BA', accession='uc021tnz.1', hgvsGenomic='g.4836699C>G', hgvsCdna='c.800C>G', hgvsProtein='p.(Ser267*)', distanceFromNearestGene=-2147483648}, TranscriptAnnotation{variantEffect=NON_CODING_TRANSCRIPT_EXON_VARIANT, geneSymbol='GP1BA', accession='uc021toa.1', hgvsGenomic='g.76358512G>C', hgvsCdna='n.437G>C', hgvsProtein='', distanceFromNearestGene=-2147483648}]}]
```

1902_ensembl.ser:
```
[VariantAnnotation{genomeAssembly=hg19, chromosome=17, chromosomeName='17', start=4836699, ref='C', alt='G', geneSymbol='GP1BA', geneId='ENSG00000185245', variantEffect=STOP_GAINED, annotations=[TranscriptAnnotation{variantEffect=STOP_GAINED, geneSymbol='GP1BA', accession='ENST00000329125.5', hgvsGenomic='g.4836699C>G', hgvsCdna='c.800C>G', hgvsProtein='p.(Ser267*)', distanceFromNearestGene=-2147483648}]}]
```
1902_refseq.ser:
```
[VariantAnnotation{genomeAssembly=hg19, chromosome=17, chromosomeName='17', start=4836699, ref='C', alt='G', geneSymbol='GP1BA', geneId='2811', variantEffect=STOP_GAINED, annotations=[TranscriptAnnotation{variantEffect=STOP_GAINED, geneSymbol='GP1BA', accession='NM_000173.5', hgvsGenomic='g.4836699C>G', hgvsCdna='c.800C>G', hgvsProtein='p.(Ser267*)', distanceFromNearestGene=-2147483648}, TranscriptAnnotation{variantEffect=STOP_GAINED, geneSymbol='GP1BA', accession='XM_005256611.1', hgvsGenomic='g.4836699C>G', hgvsCdna='c.887C>G', hgvsProtein='p.(Ser296*)', distanceFromNearestGene=-2147483648}]}]
```

**Comment by julesjacobsen** [comment]
Digging a bit deeper the gene ids in the UCSC data set are taken from hgdownload.soe.ucsc.edu/goldenPath/hg19/database/knownToLocusLink.txt.gz 
Searching for the GP1BA Entrez Id = 2811 reveals only one line:
```
uc021tnz.1	2811
```
which corresponds to the second transcript in the UCSC annotations, so only this transcript is assigned a geneId. Ultimately the blame falls on the UCSC data, but both Jannovar and later-on Exomiser could attempt to massage the data.

But for now, use Ensembl instead?

**Comment by pnrobinson** [comment]
We will use RefSeq by default for LIRICAL. I saw that multiple genes were "missing" in this way from the UCSC annotations. I will file a bug report with them.
