### ISSUE TITLE
Genotypes not labeled or explained in output when using YAML command

### ISSUE THREAD

**Issue by justaddcoffee** [TheJacksonLaboratory/LIRICAL#459]
For example, this run using the yaml command:
`java -jar target/LIRICAL.jar yaml -y ./no_genotype_labels_yaml.txt`
using the Pfeiffer.vcf and [this yaml](https://github.com/TheJacksonLaboratory/LIRICAL/files/3817281/no_genotype_labels_yaml.txt) produces an unlabeled bar for a genotype in FGFR2 that LIRICAL thinks is relevant:
![Screen Shot 2019-11-06 at 3 43 33 PM](https://user-images.githubusercontent.com/150311/68348229-3d3def00-00ae-11ea-8b6f-9bc35110b908.png)

Compare with the same analysis using this phenopacket command: 
`java -jar target/LIRICAL.jar phenopacket -p ./genotype_label_phenopacket_example.txt -e data/1909_hg19`
using [this nearly equivalent phenopacket](https://github.com/TheJacksonLaboratory/LIRICAL/files/3817286/genotype_label_phenopacket_example.txt) we produce this output with a labeled bar for the FGFR2 genotype, along with a table row with info about the genotype:

![Screen Shot 2019-11-06 at 4 08 42 PM](https://user-images.githubusercontent.com/150311/68349138-f56c9700-00b0-11ea-894d-8b6b931473ad.png)

**Comment by justaddcoffee** [comment]
[This](https://github.com/TheJacksonLaboratory/LIRICAL/blob/1565b5f06730a9f4c0c460254c2d6b4b47fbf866/src/main/java/org/monarchinitiative/lirical/cmd/YamlCommand.java#L128) is possibly the problem - in `yaml` mode, we are always calling `buildPhenotypeHtmlTemplate` or `buildPhenotypeTsvTemplate` even if there is genotype info. 

If `this.phenotypeOnly` is `false` these should be  `buildGenoPhenoHtmlTemplate` or `buildGenoPhenoTsvTemplate`

**Comment by pnrobinson** [comment]
I found the bug (finally, it really took two weeks to overcome this stupidity...)

**Comment by justaddcoffee** [comment]
+1
