### ISSUE TITLE
logger error

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/LIRICAL#490]
When I am running LIRICAL download, the first logger message is error. Download is successful. Not sure what the error is for.

[ERROR] HpoDownloader - HpoDownloader.javaorg.monarchinitiative.lirical.io.HpoDownloader.<init>(HpoDownloader.java:47) - overwrite=false
[==================================================]   100%     
[INFO] Downloaded hp.obo
[==================================================]   100%     
[INFO] Downloaded phenotype.hpoa
[INFO] Downloaded Homo_sapiens_gene_info.gz
[INFO] Downloaded mim2gene_medgen
LIRICAL: Elapsed time was 8.477 seconds.

**Comment by justaddcoffee** [comment]
> [ERROR] HpoDownloader - HpoDownloader.javaorg.monarchinitiative.lirical.io.HpoDownloader.(HpoDownloader.java:47) - overwrite=false

That is a call to error() that should be a call to info() - should be harmless, but probably should change this. Made a PR:
https://github.com/TheJacksonLaboratory/LIRICAL/pull/491

**Comment by pnrobinson** [comment]
thanks, @justaddcoffee! fixed!
