### ISSUE TITLE
VCF file is available at /path/to/data/Pfeiffer.vcf

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/LIRICAL#492]
@pnrobinson @justaddcoffee 
In documentations:
 https://lirical.readthedocs.io/en/latest/phenopacket-hpo.html 
and  
https://lirical.readthedocs.io/en/latest/phenopacket-vcf.html, 

it is written that "VCF file is available at /path/to/data/Pfeiffer.vcf." Does it mean that when data directory is downloaded by the user, pfeiffer.vcf is also downloaded?  I only see pfeiffer.json and pfeifferNoVcf.json in /test/resources/phenopacket.

**Comment by justaddcoffee** [comment]
I don't think we've included Pfeiffer.vcf, but if we have the data rights we maybe should include this

**Comment by pnrobinson** [comment]
/path/to/data/ is intended to be an example only. There is no path that starts with /path !!
maybe we should write /example/path/... ?

**Comment by vidarmehr** [comment]
I thought /path/to/data/ is the path to the Exomiser data. If you want the user to test LIRICAL on Pfeiffer.vcf, then I think it is better to put it in /example/path/....

**Comment by pnrobinson** [comment]
I have changed everyting to /example/path/...
