### ISSUE TITLE
output file null.html

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/LIRICAL#493]
@pnrobinson @julesjacobsen 

java -jar target/LIRICAL.jar yaml -y simple.yml

creates the output file null.html. Is the output file supposed to be called null?

**Comment by justaddcoffee** [comment]
This seems to happen if `prefix:` is not specified in the yaml file. I think this should be lirical.html instead of null.html

**Comment by justaddcoffee** [comment]
Here's a PR https://github.com/TheJacksonLaboratory/LIRICAL/pull/494

**Comment by pnrobinson** [comment]
fixed, thanks
