### ISSUE TITLE
Tutorial:Set up

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/LIRICAL#497]
@pnrobinson 
I am following the Tutorial on https://lirical.readthedocs.io/en/latest/tutorial.html:

In Set up: "Follow the instructions on Tutorial to install the Exomiser database and set up LIRICAL."
By clicking on Tutorial, we should be referred to https://lirical.readthedocs.io/en/latest/setup.html, but it goes to the same page https://lirical.readthedocs.io/en/latest/tutorial.html.

**Comment by pnrobinson** [comment]
fixed
