### ISSUE TITLE
Tutorial: Running LIRICAL

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/LIRICAL#499]
@pnrobinson 
$ java -jar LIRICAL.java -p LDS2.json -x LDS2

should be changed to:

$ java -jar target/LIRICAL.jar phenopacket -p LDS2.json -x LDS2 -e /path/to/exomiser-data/

**Comment by vidarmehr** [comment]
@pnrobinson 
Maybe have another command when the vcf file is not available.
$ java -jar target/LIRICAL.jar phenopacket -p LDS2.json -x LDS2

**Comment by pnrobinson** [comment]
fixed!

**Comment by vidarmehr** [comment]
@pnrobinson 

LIRICAL.java needs to be changed to LIRICAL.jar

**Comment by pnrobinson** [comment]
fixed this time!
