### ISSUE TITLE
Problem with link to VCF in tutorial?

### ISSUE THREAD

**Issue by justaddcoffee** [TheJacksonLaboratory/LIRICAL#504]
I can't seem to download the VCF file linked in the tutorial:
https://figshare.com/account/articles/10636556

I'm getting a 404 when I log in and try this URL

**Comment by vidarmehr** [comment]
Would you please try https://figshare.com, create an account and then in search menu, type LDS2. I think you will be able to find the vcf file.

**Comment by justaddcoffee** [comment]
Thanks Vida! When I log in, the link above is still a 404, but after a search I find this URL, which works:
https://figshare.com/articles/LDS2_vcf/10636556

I'll make a PR to point to this URL, and @pnrobinson can change this if he'd like to move this VCF to a JAX server
