### ISSUE TITLE
Maven assumed to be installed

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/LIRICAL#505]
Hi @pnrobinson ,
I'm reading the tutorial and the page [Setting up LIRICAL](https://lirical.readthedocs.io/en/latest/setup.html#rstsetup) assumes that Maven is installed in the system. I think this is actually never true by default on UNIX/Windows so a [reference to Maven installation](https://maven.apache.org/install.html) could be maybe helpful.

**Comment by ielis** [comment]
Hm.. this actually probably also applies to `git`.

**Comment by ielis** [comment]
Ou, actually maven is mentioned lower. So I do not know. Please decide if that's enough.

**Comment by pnrobinson** [comment]
I agree. We should probably say that most users should just download the release though!

**Comment by pnrobinson** [comment]
I added a section with prerequisites.
