### ISSUE TITLE
Make release tag and use it in tutorial

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/LIRICAL#506]
The part [Installation](https://lirical.readthedocs.io/en/latest/setup.html#installation) contains a snippet below.

```bash
$ git clone https://github.com/TheJacksonLaboratory/LIRICAL.git
$ cd LIRICAL
$ mvn compile
$ mvn package
$ java -jar target/LIRICAL.jar
$ Usage: <main class> [options] [command] [command options]
  Options:
    -h, --help
      display this help message
  (...)
```

This will build and run the latest version of the code from `master`. I think we should tag a specific commit with e.g. `v1.0.0-RC4` tag and add a line `git checkout v1.0.0-RC4` (or similar) to the snippet.

**Comment by ielis** [comment]
Also, the line `mvn compile` is redundant in this snippet.

**Comment by pnrobinson** [comment]
@ielis  -- We will shortly be releasing version 1.0.0 -- this was the last RC. 
I seem to recall that it was necessary to first do mvn compile because of the protobuf. Just doing mvn build resulted in an error. Can you confirm you were trying from a fresh build?

**Comment by ielis** [comment]
As far as I know, `mvn compile` is necessary if you want to run the app from IntelliJ as an Application. From some reason, `*.proto` files are not compiled before running the app in IntelliJ and therefore it fails unless you run `mvn compile` beforehead.

It is weird that it this is an issue in Lirical, we do not use any `*.proto` files AFAIK and the generated sources/ protobuf classes from Exomiser should already be present in Exomiser JARs.

[Maven lifecycle](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) reference states in section Using Command Line Calls , that `mvn install` will implicitly run `mvn validate, compile, test, package`, etc.. So if you have `mvn compile; mvn package` in the snippet, the first command is redundant. 
And yes, I was trying from a fresh build - `mvn clean package` worked.

**Comment by pnrobinson** [comment]
revised the docs!
I am less convinced about tagging the release -- the tutorial should work for all versions, and if there is a change in the API we should change the online tutorial. 
We should tag the final version of the code that is used for the published analysis. I am guessing this will be v.1.0.1 because we may change some things at the revision phase. I will release v.1.0.0 by Monday.
