### ISSUE TITLE
Running PhenopacketGenerator

### ISSUE THREAD

**Issue by vidarmehr** [TheJacksonLaboratory/LIRICAL#516]
@pnrobinson
I submitted this issue in https://github.com/TheJacksonLaboratory/PhenopacketGenerator/issues/14. But, I submit it here as well:

To run PhenopacketGenerator, the command:

java -jar Phenopacket-Generator-0.0.3.jar

should be changed to:

java -jar Phenopacket-Generator-0.0.5.jar

**Comment by pnrobinson** [comment]
Thanks, Vida. Let's actually remove the version from the program name it is unnecessarily complicated.

**Comment by pnrobinson** [comment]
done
