### ISSUE TITLE
Genotype of individual not considered in generating differential diagnoses

### ISSUE THREAD

**Issue by oleraj** [TheJacksonLaboratory/LIRICAL#532]
I noticed while testing the RAG1 patient VCF (as described in #528), that the first time it generated 6 diagnoses with > 95% posterior probability (4 with 100% posterior probability), none of which was RAG1.  When you look down at the details of the variants for the genes, there were many pathogenic variants in genes such as PGM3 or CTLA4, with "1" in the Pathogenicity column but in the genotype column, it said the patient was "HOMOZYGOUS_REF" for all of these.  e.g.,
![image](https://user-images.githubusercontent.com/10860409/79021937-d8019480-7b4a-11ea-8fe8-89a7d426c8fc.png)

The reason for this is that I made this proband VCF as a subset from a larger VCF that includes patients with various immune disorders and didn't filter out the variants where the patient was homozygous reference.  The workaround I found was to remove these (with bcftools view `-e "AC==0"`) and then RAG1 shows up as the top-ranked gene.  But it seems like a good idea to have LIRICAL check to make sure that the patient has the correct genotype for the variant in the related gene during the differential diagnosis.

**Comment by pnrobinson** [comment]
@oleraj  Were you using a multi-sample VCF file? This is actually not supported yet, but is one of the next improvements for this tool. Or were you creating a single-sample VCF file but some 0/0 genotypes remained?

**Comment by oleraj** [comment]
The latter -- single-sample VCF but some 0/0 genotypes remained.  Maybe this will be fixed once multi-sample VCF support is implemented?  If that's the case I'm fine with just using the workaround to make sure there are no 0/0 genotypes for now.

**Comment by pnrobinson** [comment]
This is now fixed in release v1.1.1
https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v1.1.1

**Comment by oleraj** [comment]
FYI, I tested this and it works.  Thanks for the fix!
