### ISSUE TITLE
compositeLR Calculation Discrepancy

### ISSUE THREAD

**Issue by Rob-Schuetz** [TheJacksonLaboratory/LIRICAL#551]
Hello,

In both the html and the tsv output, the compositeLR seems to be calculated according to the following formula:
compositeLR = (genotypeLR)^2 * phenotypeLR

Rather than the published formula:
compositeLR = genotypeLR * phenotypeLR

So it seems that the genotypeLR is being counted twice.

Let me know if there is something I am misunderstanding.

Thanks,
Rob

**Comment by pnrobinson** [comment]
@Rob-Schuetz sorry for the late reply -- I am not sure I understand? Can you specify?
Note that the LRs as shown in the output are log10(LR), but this is not an answer to your question.
