### ISSUE TITLE
HTML output failing to render

### ISSUE THREAD

**Issue by Rob-Schuetz** [TheJacksonLaboratory/LIRICAL#553]
Hello,

When executing LIRICAL for our cohort, 7.3% of the cases had truncated html output.  This seems to have been caused by a transcript mapping issue in the variant table.  The tsv output for these failed cases is not truncated.

I've attached an example of the failed output for your reference.  The error seems to be occurring in the summary of the 3rd ranked candidate disease. Github won't let me attach the html, so I printed it to a PDF and attached that.  Let me know if you'd like the html output and I can send it to you.
[truncated.pdf](https://github.com/TheJacksonLaboratory/LIRICAL/files/7009607/truncated.pdf)

Thanks,
Rob

**Comment by pnrobinson** [comment]
thanks for the feedback, sorry about the apparent bug, I will look into this during the week!

**Comment by pnrobinson** [comment]
Please see https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v1.3.4 @Rob-Schuetz
