### ISSUE TITLE
no output for variant

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/LIRICAL#555]
Possible bug with this variant (no output)
```
##fileformat=VCFv4.3
##Variant Recoder
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	MG107646
1	152285076	107646	CACTG	C	30	PASS	.	GT	0|1
```

**Comment by ielis** [comment]
The variant [is annotated](https://www.ncbi.nlm.nih.gov/clinvar/variation/16320/) with conflicting pathogenicity interpretation and, therefore, does not qualify as ClinVar pathogenic or deleterious by other means under current rules.

In result, no output is probably the right output.

Pls reopen and comment if you disagree.
