### ISSUE TITLE
Output features request

### ISSUE THREAD

**Issue by seoanezonjic** [TheJacksonLaboratory/LIRICAL#557]
Hi LIRICAL team
I'm using your tool right now and I think that it is very useful in my work. In fact, I would like to ask for two features:

- Obtain in one execution both output formats, html and tsv. For several cases I need the html reports to give them to clinicians and the tsv files for automatic downstream analysis.
- The tsv output lacks of phenotype data and I'm very interested in the values encoded in the phenotype histogram for each disease of the html report. I think that a phenotype.tsv file with this information would be very useful (For example, there is a phenotype that always has bad LR values? These kind of details could help in diagnosis and in phenotyping process).

Thank you in advance
Pedro Seoane

**Comment by seoanezonjic** [comment]
Inspecting the Lirical code seems to me that  using  both, --html and --tsv flags, the two files should be generated but it is not. There is any problem with this configuration?

**Comment by ielis** [comment]
Hi Pedro, again, sorry for a long reaction delay. We've updated the code & the docs a lot and we published a [new release](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.0-RC2). Please check the documentation [here](https://thejacksonlaboratory.github.io/LIRICAL/latest).

The new code base supports multiple output formats, all of which can be written out at the end of the analysis. See more info [here](https://thejacksonlaboratory.github.io/LIRICAL/latest/output.html).

Thanks & all the best,
Daniel

**Comment by iimpulse** [comment]
#607
