### ISSUE TITLE
How do I adjust the version of Exomiser

### ISSUE THREAD

**Issue by BioHuangDY** [TheJacksonLaboratory/LIRICAL#558]
Now the version of Exomiser has been upgraded from 12.1.0 to 13.0.1, more than 2 years have passed. I tried to install Exomiser 12.1.0, but kept getting errors. The error is as follows：
     [ERROR] PROTOC FAILED: ~/software/Exomiser/Exomiser-12.1.0/exomiser-core/target/protoc-plugins/protoc-3.7.0-linux-x86_64.exe: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

However, when I install Exomiser 13.0.1 I get no errors. But LIRICAL need Exomiser12.1.0. I tried to change the version of Exomiser in pom.xml to 13.0.1, but I still get an error when I install LIRICAL.   Can I ask if I use Exomiser 13.0.1 version in LIRICAL？

**Comment by ielis** [comment]
Hi @BioHuangDY we made a new LIRICAL release today. Despite using the Exomiser variant database in the analysis, the new release does not depend on Exomiser code. Therefore, the build should work on your side now (e.g. the latest `master`). Can you give it a try?

**Comment by BioHuangDY** [comment]
Dear Danis:
 Thank you for your notice. I will try the new version of LIRICAL soon.

Daoyi Huang

发件人: Daniel Danis
发送时间: 2022年7月15日 5:07
收件人: TheJacksonLaboratory/LIRICAL
抄送: BioHuangDY; Mention
主题: Re: [TheJacksonLaboratory/LIRICAL] How do I adjust the version ofExomiser (Issue #558)

Hi @BioHuangDY we made a new LIRICAL release today. Despite using the Exomiser variant database in the analysis, the new release does not depend on Exomiser code. Therefore, the build should work on your side now (e.g. the latest master). Can you give it a try?

**Comment by BioHuangDY** [comment]
Sorry to bother you again, I have a new problem. After mvn package, BUILD SUCCESS is also displayed, but there is no LIRICAL.jar file. The installation page mentioned in the README.md file has not been updated, and the /docs/setup.rst file has not been updated, so I have no idea how to use LIRICAL. So I would like to ask if it is possible to rewrite an installation and usage guide?

**Comment by ielis** [comment]
@BioHuangDY you can download a pre-built JAR file from [Releases](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.0-RC1). However, if you absolutely want to build from source, then this will do the trick:
```shell
cd LIRICAL
./mvnw -Prelease clean package
```
