### ISSUE TITLE
Documentation update?

### ISSUE THREAD

**Issue by seoanezonjic** [TheJacksonLaboratory/LIRICAL#584]
Hi LIRICAL authors
It seems to me that the documentation in https://lirical.readthedocs.io/en/latest/ corresponds to the 1.3.4 version and that is not consistent with the new release v2.0.0-RC1. I'm very interested to use this new release. Is there any readme or doc that explain how to use this last release?
Thank you very much
Pedro Seoane

**Comment by ielis** [comment]
Hi, it's taken a lot of time but the new docs are available at https://thejacksonlaboratory.github.io/LIRICAL/latest
We moved from readthedocs to github.io. 

The docs describe the latest pre-release (`v2.0.0-RC2`) which is available from the [releases](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.0-RC2).

**Comment by iimpulse** [comment]
#607
