### ISSUE TITLE
HTML report contains unexpected text in phenotype-only mode

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/LIRICAL#610]
The HTML report for phenotype-only run contains some out-of-place info.

```bash
lirical phenopacket -p examples/LDS2.v2.json
```

the HTML report has entries like:

![image](https://user-images.githubusercontent.com/12170955/230915504-1d59b891-2a03-48f7-80de-78c2ce0bad25.png)

VCF file is not used in phenotype-only mode, we do not show LR for the associated genes, and the **n/a** *No known disease gene* statements should not be displayed.

**Comment by iimpulse** [comment]
Do we want to remove the disease gene verbiage in favor of something like phenotype only mode?

**Comment by ielis** [comment]
No, I don't think we should be adding any other verbiage at this point.
