### ISSUE TITLE
Testing Lirical 2.0, and getting VERY different results from 1.3.4 version

### ISSUE THREAD

**Issue by dovelleiro** [TheJacksonLaboratory/LIRICAL#650]
Dear guys, Lirical is an important part of my pipeline for rare diseases in neuromuscular diseases.
With the new version, I'm obtaining VERY different results. In a sample I'm using as reference (the causal variant has been verified in functional analyses), that variant was found as the first option using Lirical 1.3.4 (and other 4 prioritization tools). Using Lirical 2.0, the same variant is demoted to the 29th position. 
I can give you more details by email.
Best,
David

**Comment by ielis** [comment]
Hi @dovelleiro 
that is unexpected because I compared the benchmarks and got slightly better results for `2.0.0`, likely due to incremental updates to HPO resources.

Can you please share more details?

Thanks a lot and all the best..

**Comment by dovelleiro** [comment]
I've sent you an email to your Proton address.
D

**Comment by ielis** [comment]
Hi, sorry for taking a longer time to respond. I replied to your mail.

**Comment by ielis** [comment]
Fixed by #651

@dovelleiro please reopen if the issues persist. Thank you!
