### ISSUE TITLE
Can you please provide a runnable JAR file directly

### ISSUE THREAD

**Issue by Opticalproperty** [TheJacksonLaboratory/LIRICAL#652]
Hello developer,

I attempted to package the project lirical-2.0.0 into a JAR file, but the resulting package consistently indicates that it cannot find the main method. Additionally, when I use the command ./mvnw -Prelease package for packaging, it prompts the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project lirical-core: Fatal error compiling: 错误: 无效的目标发行版：17 -> [Help 1]

Can you please provide a runnable JAR file directly? Thank you!

**Comment by ielis** [comment]
Hi @Opticalproperty 

we provide an executable in the [Releases](https://github.com/TheJacksonLaboratory/LIRICAL/releases) section (note the ZIP file in assets), and we describe how to use it in the [manual](https://thejacksonlaboratory.github.io/LIRICAL/stable/setup.html#prebuilt-lirical-executable).
