### ISSUE TITLE
Extraneous tab in TSV header

### ISSUE THREAD

**Issue by gileshall** [TheJacksonLaboratory/LIRICAL#656]
Lirical 2.0.1 generates an extraneous tab in the column header for TSV outputs.  This header specifies nine columns, but subsequent rows are only eight columns.  Loading the TSV file into Python and splitting it by the tab character returns this list:

`['rank', 'diseaseName', 'diseaseCurie', 'pretestprob', 'posttestprob', 'compositeLR', '', 'entrezGeneId', 'variants']`

Note the empty column name between `compositeLR` and `entrezGeneId`

For reference, this is how Lirical was executed:

```
lirical prioritize \
  --assembly=hg38 \
  --vcf=input_variants.vcf.gz \
  --sample-id=sample_name \
  --observed-phenotypes=HP:0001,HP:0002 \
  --sex=MALE \
  --exomiser-hg38=/lirical/lirical-cli-2.0.1/data/2302_hg38_variants.mv.db \
  --parallelism=20 \
  --prefix=sample_name_lirical \
  --output-format=tsv \
  --output-directory=lirical-results \
  --data=/lirical/lirical-cli-2.0.1/data
```

**Comment by ielis** [comment]
Please use [v2.0.2](https://github.com/TheJacksonLaboratory/LIRICAL/releases/tag/v2.0.2) and reopen if the issue persists. Thank you for reporting!
